project:
  type: website
  output-dir: docs

website:
  title: "katie"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - plants.qmd
      - fieldwork.qmd
      

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

